version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: prac-proj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: practice-project-backend/
    environment:
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: 123
      DBNAME: prac-proj

    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: practice-project-frontend/
    ports:
      - "3000:3000"

volumes:
  postgres_data:
